// components/Block/Form/Form.tsx
import stylesBlock from '../Block.module.css';
import styles from './Form.module.css';

export default function Form() {
  
  return (
    <div id='contacts-form' className={`block-form sc-hidden ${stylesBlock.block}`}>
      <div className='container'>
        <div className={stylesBlock.blockTitle}>
          <h3>Свяжитесь с нами</h3>
        </div>
        <div className={styles.description}>
          <p>Используйте данную форму, для того чтобы задать интересующий вас правовой вопрос, пожалуйста будьте настолько конкретными, на сколько это возможно.</p>
        </div>
        <div className='block-content'>
          <form action='' id='contacts' method='POST' role='form' className={styles.contacts}>
            <div className='form-group name'>
              <input type='text' className={`form-control name ${styles.text}`} name='name' id='name' placeholder='Имя*' required />
            </div>
            <div className='form-group phone-number'>
              <input type='text' className={`form-control phone ${styles.text}`} name='phone-number' id='phone' placeholder='Телефон*' required />
            </div>
            <div className='form-group email'>
              <input type='email' name='email' className={`form-control email ${styles.email}`} id='email' placeholder='E-mail' />
            </div>
            <div className='form-group question'>
              <textarea name='question' id='question' className={`form-control question ${styles.textarea}`} rows={5} placeholder='Вопрос'></textarea>
            </div>

            <button type='submit' className={`${styles.btn} btn-primary `}>Отправить</button>
          </form>
        </div>
      </div>
    </div>
  );
}

// src/components/Form.vue
<template>
  <div id="contacts-form" class="block-form block sc-hidden">
    <div class="container">
      <div class="block-title">
        <h3>Свяжитесь с нами</h3>
      </div>
      <div class="block-description">
        <p>Используйте данную форму, для того чтобы задать интересующий вас правовой вопрос, пожалуйста будьте настолько конкретными, на сколько это возможно.</p>
      </div>
      <div class="block-content">
        <form action="" id="contacts" method="POST" role="form" class="form-contacts">
          <div class="form-group name">
            <input type="text" class="form-control name" name="name" id="name" placeholder="Имя*" required />
          </div>
          <div class="form-group phone-number">
            <input type="text" class="form-control phone" name="phone-number" id="phone" placeholder="Телефон*" required />
          </div>
          <div class="form-group email">
            <input type="email" name="email" class="form-control email" id="email" placeholder="E-mail" />
          </div>
          <div class="form-group question">
            <textarea name="question" id="question" class="form-control question" rows="5" placeholder="Вопрос"></textarea>
          </div>

          <Button :primary="true" name="Отправить" />
        </form>
      </div>
    </div>
  </div>
</template>

<script setup>
import Button from '~/components/Button';
</script>

<style lang="scss">
@import '~/assets/scss/_variables.scss';

</style>
